### ISSUE TITLE
Compile time variables completely ignored

### ISSUE THREAD

**Issue by decipher3114** [neogenie/fastnum#19]
### build.rs
```rust
fn main() {
    println!("cargo::rustc-env=RUST_FASTNUM_DEFAULT_ROUNDING_MODE=Down");
    println!("cargo::rustc-env=RUST_FASTNUM_FMT_EXPONENTIAL_LOWER_THRESHOLD=16");
    println!("cargo::rustc-env=RUST_FASTNUM_FMT_EXPONENTIAL_LOWER_THRESHOLD=16");
}
```

- But, the rounding mode is still `HalfUp`

- Use Case
1000 / 94000 = 0.0106...
0.010 * 94000 = 940 [Expected]
0.011 * 94000 = 1034 [Result]

**Comment by neogenie** [comment]
It appears you're incorrectly employing `build.rs` and its environment variable settings; please review this.  I've included an illustration of rounding using a global variable defined by an environment variable.

**Comment by decipher3114** [comment]
./src/.cargo/config.toml
```toml
[env]
RUST_FASTNUM_DEFAULT_ROUNDING_MODE           = "Down"
RUST_FASTNUM_FMT_EXPONENTIAL_LOWER_THRESHOLD = "16"
RUST_FASTNUM_FMT_EXPONENTIAL_UPPER_THRESHOLD = "16"
```

debug output
```
quantity (calculated): 0.0135002097724903110032940511844876358848
quantity (rescaled): 0.014
```

Here, the expected value is `0.013`.

The issue is still present even after proper configuration of the config file.
